### PR TITLE
XCode addon folder fixes

### PR DESCRIPTION
**Pull request by dimitre**
This fixes an issue with PG where XCode addon folders full path are not preserved.
now each addon will be relative to the group ("addons folder") that by itself is related to the project.

now the arrow will point to the correct folder, and we will be able to use right click -> show in finder in any addon folder.
There will be another PR in OF repo fixing the template

Screenshot 2024-05-27 at 22 48 46

### CODE REVIEW

**Comment by dimitre** [comment]
@danoli3 this fixes some issues with frameworks and xcframeworks link phases

**Comment by armadillu** [comment]
@dimitre  Hey, I am unsure which commit this happened in, but I cant seem to add addons that are not in the "OF/addons" folder (ie "local_addons") any more. I have a bunch of automated scripts that create and compile example projects for all my addons, (which I keep in a different directory, outside the OF repo) and the latest PG fails to include them correctly now. This was working ok on PG version "34".

I have the PG xcode project setup so I can debug the creation of an example project (with custom scheme launch arguments), but man it is messy in there. 

image

I am happy to help but I wanted to check where are you with this (ie are you mid-update?)

I like the idea of making all paths relative to their "group" folders, but the problem I am seeing is that the "local_addons" main folder that is created doesn't see, to be set correctly. If I manually set it in Xcode after the project is created, it seems to work ok.

**Comment by dimitre** [comment]
Hey @armadillu I'll be investigating now. Thanks for reporting

**Comment by dimitre** [comment]
Nice, now the folder immediatly after local_addons or external_sources, or root have an absolute path. 
The rest of them are relative to group. I'll be merging soon today and it will be v.43

**Comment by dimitre** [comment]
It should be working OK now @armadillu

**Comment by armadillu** [comment]
Great, seems to work on my end!

**Pull request merged**
