### PR TITLE
cleaning up logging

### PR DESCRIPTION
**Pull request by ofZach**
I am starting to clean up command line logging and feedback.  I will open a PR on OF as well with changes to the addon

### CODE REVIEW

**Comment by ofZach** [comment]
@Daandelange (cc @kylemcdonald) these updates (besides fixing alot of the spurious / bad output) allow you to do "update" of a existing project but specify the addons via parameter (so it takes that list instead of parsing addons.make).  This should be the way to proper updating via the gui.

**Comment by ofZach** [comment]
added timing and summary at the end, ala

     1 project updated in 0.015625 seconds

**Comment by ofZach** [comment]
I'm going to merge this, there may be some more work on this but since the main OF pr was merged, this makes sense to merge and it would help to not diverge too much

**Comment by kylemcdonald** [comment]
cool! small suggestion, the duration (and its accuracy) might be a distraction rather than helpful for quick updates. maybe:

```c++
if(elapsedTime > 1) {
    cout << "in " << int(elapsedTime) << " seconds";
}
cout  << endl;
```

**Comment by ofZach** [comment]
sure good point, I'll add that...

**Pull request merged**
