### PR TITLE
update electron

### PR DESCRIPTION
**Pull request by 2bbb**
this PR is W.I.P. 

but, I feel happy If anyone can check this sometime. (because I have only macos now...)

related: #342

### CODE REVIEW

**Comment by ofTheo** [comment]
Hey @2bbb - wow!
Thanks for this. 👏

Just gave it a try. 

I had to change these lines: 
https://github.com/2bbb/projectGenerator/blob/PR/update_electronnnn/frontend/package.json#L17-L24

from 0.37.8 to 17.1.1

```
  "scripts": {
    "start": "electron .",
    "build": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --all --overwrite --electron-version=17.1.1",
    "build:osx": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=17.1.1 --platform=darwin --arch=x64",
    "build:linux32": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=17.1.1 --platform=linux --arch=ia32",
    "build:linux64": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=17.1.1 --platform=linux --arch=x64",
    "build:vs": "electron-packager . --icon=static/icon/of.ico --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=17.1.1 --platform=win32 --arch=ia32"
  },
```

Then eveything seems to work, for making projects or updating. 

Except the update multiple button ( selecting the folder seems to not work ) 

image

Can test on Windows tomorrow. 
But this is great progress!

**Comment by 2bbb** [comment]
@ofTheo 

thanks for testing!! 
and thanks telling me where the version is decided, I didn't noticed it is hard coded on build lines...

I'll fix about update multiple button.

**Comment by 2bbb** [comment]
@ofTheo
maybe feature about "update multiple" is fixed.
and I found bug on feature about "extra source path" and fixed.

please test again!

I will adopt codes from #216 and #240 if there are my mistakes or better way.

**Comment by ofTheo** [comment]
@2bbb this looks great 
The multiple examples works well now. 

The extra source paths also worked, but might need a bit of tweaking. 
( If you update a project with extra source paths, it doesn't import the extra source paths back in ).

I think it was more broken before though, so we could just merge this and do some smaller PRs for the remainder.

**Comment by 2bbb** [comment]
@ofTheo 

ok, I update and post small PRs after this PR is merged!

**Comment by 2bbb** [comment]
@dimitre 
now, we can close related PRs #215 #216 #240.

@hiroMTB @autr 
thanks for greate PRs!

**Comment by hiroMTB** [comment]
closed! thanks a lot!

**Pull request merged**
