### PR TITLE
this is a good icon

### PR DESCRIPTION
**Pull request by ofZach**
this adds a missing .icns file.  On osx this work, but I'm not 100% sure about icons on other platforms: 

screen shot 2015-10-29 at 10 07 02 am

### CODE REVIEW

**Comment by ofZach** [comment]
this PR has a funny name, but you get the idea :)

**Comment by mattfelsen** [comment]
I might be opening a whole can of worms here, but... I kind of got attached to that circular electron one with the white border, so I took a quick stab and marrying that with the OF logo. Good/bad? Also I don't know how to turn this into an .icns file but here's a 1024x1024 png

of-electron

**Comment by ofZach** [comment]
ok !  switched it up (I use icns builder)....

now looks like: 

screen shot 2015-10-29 at 10 32 40 am

**Comment by mattfelsen** [comment]
hawt

**Comment by ofZach** [comment]
merging this in now...

**Pull request merged**
