### PR TITLE
Github Actions - update linux

### PR DESCRIPTION
**Pull request by dimitre**
service not available anymore on 16.04

### CODE REVIEW

**Comment by dimitre** [comment]
@ofTheo @danoli3 can you please merge this one?
16.04 was discontinued recently
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

**Comment by ofTheo** [comment]
Hmm, looking into this more I think the issue is that the gcc that is default in Ubuntu 18.04 still has the experimental filesystem ( https://askubuntu.com/questions/1365157/upgrade-gcc-version-in-ubuntu-18-04 ). So we might need to change the way we are passing flags to the compiler. 

I'll try and fix this on the main OF repo, as OF should compile out of the box on 18-04. Once I think its working we can rerun the check here and then merge.

**Comment by dimitre** [comment]
Great! what about 20.04?

**Comment by ofTheo** [comment]
This works now with https://github.com/openframeworks/openFrameworks/pull/7013 merged

**Pull request merged**
