### PR TITLE
Remove old pg, rename electron → frontend

### LINKED ISSUE #83: merge with openFrameworks core
@ofTheo reported that it's still not super clear with the project generator how to make examples for OF when you pull from github, I feel like moving this submodule back into the core of OF would help make things more clear and easier to track the progress of this project.     it's also been tricky to have PRs across both the main OF repo and this repo when things like templates and the addon change, as well as sometimes the submodule link is out of date.  

I'm in favor of bringing this back into the core of OF and making it a bit easier to understand and use the command line tool for updating the OF examples.

### PR DESCRIPTION
**Pull request by mattfelsen**
As per https://github.com/openframeworks/projectGenerator/issues/82, this removes the legacy & simple projects. I also rename the projectGeneratorElectron folder to frontend, which I would think is more descriptive than simply "electron" (my first instinct).

It makes sense to get rid of these projects before merging back with the OF core, and closes #83

### CODE REVIEW

**Comment by ofZach** [comment]
ping @arturoc will this name change break the nightly builds?  This PR look good to me... thanks @mattfelsen !

**Comment by mattfelsen** [comment]
Oh good call, just sent a PR to the main repo to fix. Hopefully I didn't miss anything. 

https://github.com/openframeworks/openFrameworks/pull/4685

**Comment by arturoc** [comment]
that looks good, it's not mergeable with master though, can you check that? i mean this repo not your fix in create_packages, btw

**Comment by mattfelsen** [comment]
That's odd, it looks good for me?

image

**Comment by arturoc** [comment]
i'm not talking about the tests but the ability to merge it:

screenshot from 2015-12-22 11-02-38

**Comment by mattfelsen** [comment]
Sorry, should be fixed now. Was weird, I had no merge conflict when merging master into this branch. ¯\\\_(ツ)_/¯

**Comment by arturoc** [comment]
:) thanks!

**Pull request merged**
