### PR TITLE
Added drag'n'drop feature for importing (single) projects.

### PR DESCRIPTION
**Pull request by Daandelange**
I think this is ready to be merged.

### CODE REVIEW

**Comment by mattfelsen** [comment]
This looks mostly good on OS X for me, though I'm seeing a bit of funkiness on this one too. Every so often, sometimes if I'm fast and sometimes not, it seems like it's not responding to the mouse hovering over the window with a folder. Have you seen this?

dragndrop

**Comment by Daandelange** [comment]
Thanks for your feedback, it's a bit a struggle to work with webkit's HTML5 drag&drop API... lots of workarounds.

I've improved it's behaviour but I didn't succeed in making it 100% bug-free; it's hard to observe what's going wrong there, so quick it goes! Anyways, it seems to be related to some HTML elements fading in/out, and calling `dragenter`/`dragleave` in some kind of callback loop.

Moving the mouse out of the window and back again shows the modal again.

**Comment by Daandelange** [comment]
I found a better way of handling this using [jQuery.dragBetter](https://github.com/lolmaus/jquery.dragbetter/) by lolmaus which is an additional dependency under the MIT licence.
Is it OK to add it in `PG/frontend/static/js/jquery.dragbetter.js` ? 
Do I need to add any license stuff ? _(i guess: yes)_ If so, how ?

**Comment by Daandelange** [comment]
According to me this PR can now be merged.
Tested only on Mac but should work fine on Linux + Windows.
_(Maybe the jquery.dragbetter license needs to be checked ?)_

Fixes issues 130 and 134

**Comment by mattfelsen** [comment]
Finally got around to testing this (also on Mac, 10.11) and it looks good to me! I couldn't reproduce any of the weirdness I reported earlier with occasionally not responding to drag events

**Comment by arturoc** [comment]
this is not mergeable anymore, if you can bring it up to date?

**Comment by Daandelange** [comment]
I'll check it :)

**Comment by Daandelange** [comment]
@arturoc it should merge fine now. :)

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
