### PR TITLE
Removing Poco

### PR DESCRIPTION
**Pull request by dimitre**
In this PR I've removed poco funcionality, Poco::path 
regular expressions ported to std
and uuid functionality ported to the library uuidxx
some things in XCode project were manually updated so the commandLine project and OF project can be compatible in of::filesystem.

### CODE REVIEW

**Comment by dimitre** [comment]
oh I've now noticed Poco is being used for optionparser too...

**Comment by dimitre** [comment]
ok @ofTheo this is a Pocoless PG.
XCode project is a very old and full of customizations, non standard project names, some additional script phase.
One day we will have the project up to date so PG project can be regenerated with PG itself haha

**Comment by ofTheo** [comment]
Sweet! Thanks @dimitre 
It seems like it is failing a check though at the moment.

**Comment by dimitre** [comment]
Yes I think this issue was related to using an old xcode project so it doesn't invoke compile OF with the latest settings, after your c++17 PR. I'll investigate further and hopefully make it work

**Comment by dimitre** [comment]
This was the issue. Project was using a different c++ version than OF project, so things got uncompatible.
I'll merge this one now

**Comment by ofTheo** [comment]
Ahhh right. I should have realized those were C++11 errors. 
Awesome!! Great to get Poco out if there! 🎉

**Pull request merged**
