### PR TITLE
Update readme for electron app

### PR DESCRIPTION
**Pull request by mattfelsen**
First pass at adding some documentation on how to get the electron fronted up & running. Some of the docs will probably soon be outdated if folders are renamed (which I do in my forthcoming PR) and there are some steps which should get automated or have scripts for, but I believe this is what's necessary as-is, so we gotta start somewhere :smile:

### CODE REVIEW

**Comment by mattfelsen** [comment]
Helpful for issues like https://github.com/openframeworks/projectGenerator/issues/104 and https://github.com/openframeworks/projectGenerator/issues/83#issuecomment-155059903

**Comment by mattfelsen** [comment]
Pinging @danoli3 too who dug into this recently, would be good to know if this is a helpful format

**Comment by danoli3** [comment]
Awesome thanks! Makes a lot more sense :D!

**Comment by ofZach** [comment]
this looks great - thanks! merging!

**Comment by Daandelange** [comment]
Thanks, nice start! 
Maybe we could also put a link to [npm](https://nodejs.org/en/download/) which is not installed by default.

**Comment by mattfelsen** [comment]
Oh good point, I always forget that about node/npm. I'll add a note and
suggest a couple ways to install:

- easiest: from nodejs.org
- homebrew
- homebrew + npm

Is anyone aware of any node version dependencies? I've used & built the
electron app with 0.10 and 5.3 so I think we're in the clear, but just
checking

**Comment by mattfelsen** [comment]
Whopps, that's homebrew + *nvm*. Corrected

**Comment by ofZach** [comment]
one thing I'd like to mention in the readme (I am making an issue here just to remind myself to add a note) is the use of "npm-shrinkwrap.json" ie: 

https://github.com/openframeworks/projectGenerator/blob/master/projectGeneratorElectron/npm-shrinkwrap.json

to fix a bug that was building packages on osx incorrectly so they were failing on 10.8.   I think it's useful to mention this in case anyone starts manipulating the modules / etc as I'm not sure if shrinkwrap needs to be regenerated, etc. 

(also this bug might be fixed by now so if we can remove this, it make the whole thing less fragile) 

I need to do a bit of research to remember the problem and solution but I'll add this shortly.

**Comment by mattfelsen** [comment]
@ofZach I played around with shrinkwrap for a bit but could not get it to work! `npm install` works and the app starts fine, but then trying `npm shrinkwrap` from my working setup kept giving errors, mostly around a version mismatch between electron-debug 0.1.1 being wanted but electron-debug 0.2.1 being installed? Also it looks like [devDependencies are ignored for shrinkwrapping](https://docs.npmjs.com/cli/shrinkwrap#other-notes), so those might need to be moved to dependencies (I tried this, and shrinkwrap is still complaining).

So I can't really test this, and I'm not sure how to test/reproduce the issues you saw on 10.8, so I'll leave it to you to figure out :smile: Here's the bit I wrote for the readme which I'm leaving out for now, but feel free to re-use later if you like:

### This package is shrinkwrapped!

We use `npm shrinkwrap` to specify versions not only of the node modules we use directly, but their dependencies as well. If you are working on the electron app and need to add npm modules, be sure to update the shrinkwrap after and include `npm-shrinkwrap.json` in your pull request along with `package.json` and any code updates.

```
# the usual
npm install --save new-module

# do some coding, make sure everything works

# shrinkwrap it!
npm shrinkwrap

# add npm-shrinkwrap.json when you commit!
```

**Comment by ofZach** [comment]
thanks it's gonna take me a few days to get my gears cranking again.  also it looks like this issue: 

https://github.com/maxogden/electron-packager/issues/111

has been fixed upstream

https://github.com/maxogden/extract-zip/issues/6

so we might not even need shrinkwrap....   It was basically being used to point to a specific fix upstream.   gonna check....

**Comment by mattfelsen** [comment]
Gotcha. All good, I'm on a pg roll today :sunglasses:

**Pull request merged**
