### PR TITLE
open in IDE

### PR DESCRIPTION
**Pull request by ofZach**
this adds an open in IDE button on success which seems like the simplest way to add this feature (we can work on a better system post 0.9).  It only works on OSX at the moment.

screen shot 2015-10-29 at 9 38 59 am

this PR also fixes a bug with filtering out addons that causes an error when you have the array path wrong (and thus the addon array is null)

### CODE REVIEW

**Comment by ofZach** [comment]
@mattfelsen: what is the command to launch the IDE on windows ?  ie, on on osx "open .....xcodeproj"
@arturoc: what is the command to launch the IDE on linux?

**Comment by mattfelsen** [comment]
ooh, shiny! also, great question! i'll see if I can figure it out now. for linux, you can try `xdg-open $DESTINATION_PATH` from @thomasgeissl's  [comment here](https://github.com/openframeworks/projectGenerator/issues/46#issue-109543199)

**Comment by ofZach** [comment]
PS: this PR also puts the actual command line command at the bottom of the IDE message, which could be useful for debugging, etc: 

screen shot 2015-10-29 at 9 50 03 am

**Comment by mattfelsen** [comment]
+1 for that. The parentheses seem like it'd be easy to accidentally copy the closing parenthesis though?

For windows, both of these are working for me:
`start relative\path\to\project\project.sln`
or
`start C:\absolute\path\to\project\project.sln`

**Comment by ofZach** [comment]
ok added windows and linux now, invites testing ! 

@mattfelsen do you think I should drop the parens?  I kind of thought it was weird without context but maybe we can say command used:\n....... instead of parentheses)

**Comment by ofZach** [comment]
PS: for basic testing, if you are not building electron, you can replace out index.html, index.js and app.js in the nightly...

**Comment by mattfelsen** [comment]
Button is working for me, both using `npm start` and running the exe from the dist folder.

On a UX note, I think hitting the button should close the modal, just as the Close button does. It seems weird to close visual studio and see the pg with that modal still up.

And yea, no parens and a newline is what I was thinking :blush:

**Comment by ofZach** [comment]
good idea about closing the modal...  just added that.

will take a look at the parens in a sec. thanks for the feedback!

**Comment by arturoc** [comment]
we don't use codeblocks anymore in linux, the extension is qbs for qtcreator.

**Comment by ofZach** [comment]
oh ok !  let me update the labels...  is this accurate: 

screen shot 2015-10-29 at 10 14 15 am

**Comment by arturoc** [comment]
yes

**Comment by ofZach** [comment]
ok made that change !  thanks !

**Comment by mattfelsen** [comment]
very fond of [this line](https://github.com/openframeworks/projectGenerator/pull/73/files#diff-8cef9e377939ac98ef1630a154e68a07R935): `console.log("sdfsadfasdf?");`

**Comment by ofZach** [comment]
oof thanks -- cleaned it up

**Comment by ofZach** [comment]
going to merge this in so folks can test on the nightlies, etc...  I think it's ok, there might be some weird edge cases like when you build with multiple platforms or make a project that's not your default platform...

**Comment by Daandelange** [comment]
Tested and works great here :)

**Pull request merged**
