### PR TITLE
WIP - Fix paths for additional sources (XCode)

### PR DESCRIPTION
**Pull request by dimitre**
This PR already fixes some of the issues with additional source folders on XCode.
There are some minor issues to address yet

Closes : https://github.com/openframeworks/projectGenerator/issues/372
Closes : https://github.com/openframeworks/projectGenerator/issues/368
Closes : https://github.com/openframeworks/projectGenerator/issues/366

### CODE REVIEW

**Comment by dimitre** [comment]
Hey @ofTheo just to let you know I've been working on PG commandline issues, hopefully they will be solved in this PR but it got more complex than I initially thought so it is  huge 😅

**Comment by ofTheo** [comment]
Cool! 
Does this PR close any issues? 

Also for such a large number of changes, would be good to try a few different tests. 
- Make a project outside of the OF_ROOT folder structure  
- Update a project outside of the OF_ROOT 
- Use the PG frontend to update a project with additional sources 
- Try generating the examples

**Comment by dimitre** [comment]
Yes I think this closes 2 opened issues maybe some more things.
Super, those are important tests.
I finally have temporary access to a machine with vs2019, it would be great to have access to a project using "prop" files so I can compare to make it work correctly with PG

**Comment by ofTheo** [comment]
@dimitre I think a lot of @elliotwoods adding use the .prop files. 
https://github.com/elliotwoods/ofxSpout 
and
https://github.com/elliotwoods/ofxCvMin 
both use them.

**Comment by dimitre** [comment]
Closes https://github.com/openframeworks/projectGenerator/issues/366

**Comment by dimitre** [comment]
Thanks @ofTheo, now I see where props files are located in Visual Studio 2019 (Property Manager window) so they are being added correctly, finally.
I've confirmed this PR potentially closes 3 issues.

I'm investigating other addons like ofxKinectForWindows2 and I think it is not hard to be able to add a vcxproj to the generated project, automatically with PG.
Is there some "default" path for this kind of addon files? I've noticed both ofxBullet has a folder called "ofxBulletLib" and ofxKinectForWindows2 has the folder "ofxKinectForWindows2Lib". is this the additional project default folder? addonName + "Lib" ?

**Comment by 2bbb** [comment]
hi @dimitre !

this is great work!

but why do you remove many `std`...?

this may not be essential, but I want to point this.
I agree to use `using namepace std` at implementation file (.cpp), but I can't agree do it on header.
so, maybe you do because those are only used in PG project, but it's not good manner I think...

I can't judge what we need to choice, this is only pointing out what I noticed.

thanks

**Comment by dimitre** [comment]
Thanks @2bbb I can revert that. I've just thought this is not a problem since the PG project is a closed one, we usually don't reuse components from there in other OF projects.
Does it make sense? or maybe there are more things to consider?

**Comment by dimitre** [comment]
Hello @ofTheo let's enable discussions in this repository? 
Do you prefer to keep all centered in OF one?
I have some progress in this PR and wanted to ask / share / centralize info about PG development and usage.
Thanks!

**Comment by ofTheo** [comment]
good to merge @dimitre ?

**Comment by dimitre** [comment]
Hey @ofTheo I had to fix some more things yesterday and today.
Now I finally think it is good to merge.
I'm planning of merging today after passing the tests, is this ok for you?

**Pull request merged**
