### PR TITLE
add vscode support 🚜under development🔨

### PR DESCRIPTION
**Pull request by hiroMTB**
Not finished yet, do not merge, please🙏

🚦 STATUS
- [x] generate project
- [x] update project
- [x] test with addon
- [x] test recursive feature
- [x] test on OSX
- [ ] test on Windows
- [x] test on Linux
- [ ] test on RPi
- [ ] send related PR to oF main repo

 🎨 Update commandLinePG project files
Need to add vscodeProject.h/.cpp
- [x] Xcode
- [ ] visual studio
- [ ] Qt
- [ ] Code Blocks !?
 
⚠️ NOTICE
Project's template files must be located in [/openFrameworks/scripts/templates](https://github.com/openframeworks/openFrameworks/tree/master/scripts/templates)/vscode. I put these in this repo (/templates/vscode) in order to test quickly and deploy later. 

💡 vscode project configuration
I refer to following repos. Still not sure about the best settings.
https://github.com/npisanti/of_vscode
https://github.com/robertofazio/openFrameworks_VisualStudioCode_Example
https://github.com/hiroMTB/vscode_oF

 ✏️ Command line arguments
Please make sure to pass -p"vscode" argument when you debug command line executable.
In Xcode, we can set at Scheme.
-v
-o"/path/to/oF"
-a""
-p"vscode"
"/path/to/of/app/myApps/mySketch"

❗️Edit
- Please make a empty "vscode" folder under /openFrameworks/scritps/templates for frontend app test.

### CODE REVIEW

**Comment by arturoc** [comment]
Hiroshi, about the target platform, until now we've had a default config for each platform so for linux is makefiles + qt for osx makefiles + xcode...

But we've never supported more than one possible ide option per platform until now.

I see two ways to solve it:

- We add vscode files by default when creating a project along with the other defaults we have right now, that way projects will work right away with any of the supported IDEs

- We have a default and this constants, OF_TARGET_LINUX... only refer to the default but then we have ways to specify an alternartive IDE we would need to pass a parameter to the command line PG specifying the IDE apart from the platform and the command line PG (and ofxProjectGenerator) handles that. If none is passed then it uses the defaults.

I think option number 2 makes more sense

**Comment by hiroMTB** [comment]
@Daandelange 
Thanks!
Right now PG generate Qt project together with make files. And about Open IDE button, when we don't have Visual Studio 2017 or Xcode installed, the button does not work. So I guess it's okay to use "code" command here. But we can roll back if there is a good solution for this. :-)

@arturoc 
Thanks, I see the point. Option #2 sounds better for me too.
vscode needs invisible folder of /.vscode. And it could contain huge files(sometimes several GB) which stores autocomplete database(probably). So it can be annoying to have this invisible folder for those who don't use vscode.

To implement option #2, I assume we need like following changes,
- Frontend: provide one more dropdown list to let user select altanative IDE option
- CommnadLine: receive additional argument, e.g. ./projectGenerator  -a' ' -p'linuxarmv6l' -i"vscode"

hmm...

**Comment by hiroMTB** [comment]
I made a google spreadsheet for overview of current situation.
https://docs.google.com/spreadsheets/d/143Dg0eVCigOgk1a2mTIAkuHuefuaJtdcYnJKzphkHl0/edit?usp=sharing

**Comment by arturoc** [comment]
It might be that we don't really need a second dropdown, if the config files for every platform are the same then vscode can just be one more option in the dropdown we have until now as you have it.

**Comment by hiroMTB** [comment]
ok!
Will try to implement that way.

**Comment by hiroMTB** [comment]
I sent 2 more PR related to organize more IDEs. (sorry for mess 😅)

#203 strip ofTargetPlatform
#204 add quick implementation of altanative IDE option

#203 looks simpler and more flexible for me.

**Comment by hiroMTB** [comment]
We've concluded that we add vscode support via -t, -template option of command line PG.
And we do not change PG in the meant time.
For detailed discussion at #203.

**Comment by Daandelange** [comment]
Ok, that went fast ! :)
Thanks, great overview and insights, sounds good to me too.
Let me know if you need help implementing a dropdown in the Electron GUI, I can make some time.

**Comment by hiroMTB** [comment]
Thanks!
I'm preparing frontend at here.

https://github.com/hiroMTB/projectGenerator/tree/feature-add-template-dropdown-to-frontend?files=1

Gui has been done, but I need to parse template.config to make valid drop down list for each platform.

**Comment by NicTanghe** [comment]
Yeah so i dont realy count the current state of this as fixed.
It seems what is needed realy is .sln support for c++ in vscode.
I'm not a good enaugh coder and i have no idea what whould be needed for this to be supported.

Maybe i'm wrong and this can be fixed by simply using the mysys2 64bit install.
It is however verry unclear and i whould apreciate more info and clarity on the current state of this project.

incase it wasn't clear my os is windows 10.

**Comment by hiroMTB** [comment]
Hello, this PR is an old one which I decided not to merge because of the technical issue.
Instead, we worked (and finished)on [this PR](https://github.com/openframeworks/projectGenerator/pull/206)

And it was merged to master and included in official zip release too.
Please download and use latest PG frontend with advanced tick box on.

**Comment by NicTanghe** [comment]
thank you verry much about the tick the advanced tick box advice !
evrything is working excellently.
Also thank you verry much!! for all the effort you put into compatibility with vscode.

**Comment by dimitre** [comment]
I'm just linking this new discussion related to the same theme here, 
in the case anybody wants to review or have suggestions on the ongoing effort to support VSCode (and Intellisense) in projectGenerator
https://github.com/openframeworks/openFrameworks/issues/7677

**Pull request closed without merging**
