### PR TITLE
[W.I.P.] more frontend refactoring

### PR DESCRIPTION
**Pull request by 2bbb**
refactoring to find bug easily, and some bug was fixed.

### CODE REVIEW

**Comment by 2bbb** [comment]
@ofTheo 
maybe good time to merge now.
please test on windows if you can...!!

**Comment by ofTheo** [comment]
Thanks @2bbb !!
Will merge now.

**Comment by ofTheo** [comment]
Windows seem to work well with these changes! 
Absolutely no issues from the projects I ran or examples updated. 

ps: Windows/VS OF seem to compile so much faster now on VS 2022 - I think maybe thanks to @dimitre's header cleanup 💪

**Comment by dimitre** [comment]
Great work @2bbb! Glad Electron is finally up to date.
It would be great if sometime in the future we could port PG frontend to https://tauri.app
so we get a few megabytes app instead of 340. 
I tell this only to share this modern alternative to Electron but I myself can't do a thing in npm, electron etc.

**Pull request merged**
