### PR TITLE
XCode pbxproj in Json format

### PR DESCRIPTION
**Pull request by dimitre**
To test this fork the pbxproj have to be converted to JSON format with this commands:
```
plutil -convert json scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj 
plutil -convert json scripts/templates/ios/emptyExample.xcodeproj/project.pbxproj 
```

it is meant to be merged together with https://github.com/openframeworks/openFrameworks/pull/7028

### CODE REVIEW

**Comment by dimitre** [comment]
@ofTheo I've made a script to benchmark generation of all examples, both in current PG and this Json fork.
and here is the results, approximate 6x faster :)
```
time ./pg.py
./pg.py  6.12s user 2.32s system 96% cpu 8.763 total
./pg.py  50.83s user 2.22s system 99% cpu 53.290 total
```

this is the script to invoke pg for all dirs (excluding android and ios)
```python
#!/usr/bin/env python3
import os

dir = 'examples'
files = []
for d in os.listdir(dir):
    if d != 'android' and d != 'ios':
        folder = dir+'/'+d
        if os.path.isdir(folder):
            for f in os.listdir(folder):
                subfolder = folder + '/' + f
                if os.path.isdir(subfolder):
                    files.append(subfolder);

for f in files:
    command = 'cd '+f+'; ../../../apps/projectGenerator/commandLine/bin/projectGenerator.app/Contents/MacOS/projectGenerator -o"../../../" .'
    os.system(command)
```

**Comment by ofTheo** [comment]
@dimitre that's awesome!
Will help with the packaging and CI for sure. 👍

**Comment by dimitre** [comment]
Hey @ofTheo answering your questions about any downsides: I don't even consider a downside but:
At first the file itself can be less readable, because of how json is structured coming from plutil (command line to convert pbxproj formats)
In other hand we are now able to edit emptyExample project directly in XCode if needed, and we can use a json ident/format tool to organize it better if needed too.

the good things are:
— performance (many times faster on building openCV projects, no xml traversing)
— not using pugixml anymore in xcodeProject (there are some deprecated functions being used there)
— more compact code.

if this branch has future I can work in cleaning up some personal comments to convert the draft into ready for review

**Comment by ofTheo** [comment]
Hey @dimitre  - I am good to merge this if its ready? 
I am guessing we'll need to update the template in the main repo too and once this is merged we might find some bugs when its being used to generate all the examples.

**Comment by dimitre** [comment]
Hey @ofTheo I've just cleaned up previous comments and made the PR in openFrameworks git too.
I've tested a few things, I will test more extensively in monday, so do as you prefer, it can be merged now or later.

**Comment by dimitre** [comment]
Great @ofTheo, super happy about this one! 
Maybe it is time to point projectGenerator submodule to this latest commit, once we already migrated the template on openFrameworks too.

**Pull request merged**
