### PR TITLE
Add simple readme

### PR DESCRIPTION
**Pull request by kr15h**
There were problems compiling this and we figured it out during the workshop and I just wanted to post it here instead of somewhere deep in the forums.

### CODE REVIEW

**Comment by arturoc** [comment]
Those scripts are really meant to be used on the servers that build the release although they should work on any computer really, the usual ways of building a project, using makefiles or the xcode or qtcreator projects should work fine for the project generator too.

which problems where you having?

**Comment by kkshmz** [comment]
Is this not going to be added or ?

**Comment by kr15h** [comment]
Will iterate on this.

**Comment by haschdl** [comment]
@arturoc @kr15h  is the proposed README containing outdated/incorrect info? maybe just reject the PR, it's two years old now :)

**Pull request closed without merging**
